update edge

diff --git a/tools/docker/edge/ui/root/etc/s6-overlay/s6-rc.d/init-keygen/run b/tools/docker/edge/ui/root/etc/s6-overlay/s6-rc.d/init-keygen/run
--- a/tools/docker/edge/ui/root/etc/s6-overlay/s6-rc.d/init-keygen/run
+++ b/tools/docker/edge/ui/root/etc/s6-overlay/s6-rc.d/init-keygen/run
@@ -2,12 +2,12 @@
 # shellcheck shell=bash
 
 SUBJECT="/C=DE/ST=HH/L=Hamburg/O=openems.io/OU=OPENEMS Server/CN=*"
-if [[ -f /config/keys/cert.key && -f /config/keys/cert.crt ]]; then
-    echo "using keys found in /config/keys"
+if [[ -f /etc/nginx/keys/cert.key && -f /etc/nginx/keys/cert.crt ]]; then
+    echo "using keys found in /etc/nginx/keys"
 else
-    echo "generating self-signed keys in /config/keys, you can replace these with your own keys if required"
+    echo "generating self-signed keys in /etc/nginx/keys, you can replace these with your own keys if required"
     rm -f \
-        /config/keys/cert.key \
-        /config/keys/cert.crt || true
-    openssl req -new -x509 -days 3650 -nodes -out /config/keys/cert.crt -keyout /config/keys/cert.key -subj "$SUBJECT"
+        /etc/nginx/keys/cert.key \
+        /etc/nginx/keys/cert.crt || true
+    openssl req -new -x509 -days 3650 -nodes -out /etc/nginx/keys/cert.crt -keyout /etc/nginx/keys/cert.key -subj "$SUBJECT"
 fi
